name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Create pdf
        uses: tj-actions/puppeteer@v4
        id: puppeteer
        with:
          files: |
            test/test.js

      - name: Copy pdf
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf
          destination: test.pdf

      - name: Submit pdf
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: test
          target-folder: output
          clean: true
          branch: main
          commit-message: ok