name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run test
        uses: tj-actions/puppeteer@v4
        id: puppeteer
        with:
          files: |
            test/test.js

      - name: Copy test output
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: test
          target-folder: output
          clean: true
          branch: main
          commit-message: ok