name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: node test/test.js

      - name: Submit pdf
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: test
          target-folder: output
          clean: true
          branch: main
          commit-message: ok